In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [3]:
#read data about all users visits into df_en
df_en=pd.read_csv('takehome_user_engagement.csv')
df_en['time_stamp']=pd.to_datetime(df_en['time_stamp'])
df_en.head(20)

time_stamp  user_id  visited
0  2014-04-22 03:53:30        1        1
1  2013-11-15 03:45:04        2        1
2  2013-11-29 03:45:04        2        1
3  2013-12-09 03:45:04        2        1
4  2013-12-25 03:45:04        2        1
5  2013-12-31 03:45:04        2        1
6  2014-01-08 03:45:04        2        1
7  2014-02-03 03:45:04        2        1
8  2014-02-08 03:45:04        2        1
9  2014-02-09 03:45:04        2        1
10 2014-02-13 03:45:04        2        1
11 2014-02-16 03:45:04        2        1
12 2014-03-09 03:45:04        2        1
13 2014-03-13 03:45:04        2        1
14 2014-03-31 03:45:04        2        1
15 2013-03-19 23:14:52        3        1
16 2013-05-22 08:09:28        4        1
17 2013-01-22 10:14:20        5        1
18 2013-12-19 03:37:06        6        1
19 2012-12-20 13:24:32        7        1

In [4]:
#function has_week is calculating engagement of a user in 7 day period
def has_week(series):
    #print(series)
    data = np.sort(series)
    #return len(data)
    prev_prev_day = None
    prev_day = None
    for curr_day in data:
        if prev_prev_day is not None:
            if (curr_day - prev_prev_day)/ np.timedelta64(1, 'D') <= 7:
                #print(curr_day, prev_prev_day)
                return True
        prev_prev_day = prev_day
        prev_day = curr_day
    return False

In [5]:
#find all users who are engaged during a week
df_all = df_en.groupby('user_id')['time_stamp'].agg([['has_week', has_week]])
df_all.head()

has_week
user_id          
1           False
2            True
3           False
4           False
5           False

In [6]:
df_true = df_all[df_all['has_week']==True]
df_true.reset_index(level=0, inplace=True)
#df_true
df_true['user_id'].values
#print(df_true.columns)

array([    2,    10,    20, ..., 11969, 11975, 11988], dtype=int64)

In [7]:
#read all users data into df_users
df_users=pd.read_csv('takehome_users.csv', encoding='latin-1')
df_users.tail()

object_id        creation_time           name  \
11995      11996  2013-09-06 06:14:15   Meier Sophia   
11996      11997  2013-01-10 18:28:37  Fisher Amelie   
11997      11998  2014-04-27 12:45:16    Haynes Jake   
11998      11999  2012-05-31 11:55:59   Faber Annett   
11999      12000  2014-01-26 08:57:12     Lima Thaís   

                           email     creation_source  \
11995      SophiaMeier@gustr.com          ORG_INVITE   
11996     AmelieFisher@gmail.com  SIGNUP_GOOGLE_AUTH   
11997        JakeHaynes@cuvox.de        GUEST_INVITE   
11998         mhaerzxp@iuxiw.com   PERSONAL_PROJECTS   
11999  ThaisMeloLima@hotmail.com              SIGNUP   

       last_session_creation_time  opted_in_to_mailing_list  \
11995                1.378448e+09                         0   
11996                1.358275e+09                         0   
11997                1.398603e+09                         1   
11998                1.338638e+09                         0   
11999                1.390727e+09                         0   

       enabled_for_marketing_drip  org_id  invited_by_user_id  
11995                           0      89              8263.0  
11996                           0     200                 NaN  
11997                           1      83              8074.0  
11998                           0       6                 NaN  
11999                           1       0                 NaN

In [8]:
#creat new column 'adopted' 
df_users['adopted'] = 0 

In [9]:
#fill 'adopted' with the data calculated above
for entry in df_users['object_id']:
    if entry in df_true['user_id'].values:
        df_users.loc[df_users['object_id']==entry, 'adopted']=1

In [10]:
df_users.columns

Index(['object_id', 'creation_time', 'name', 'email', 'creation_source',
       'last_session_creation_time', 'opted_in_to_mailing_list',
       'enabled_for_marketing_drip', 'org_id', 'invited_by_user_id',
       'adopted'],
      dtype='object')

In [11]:
df_users[['creation_time','last_session_creation_time']]

creation_time  last_session_creation_time
0      2014-04-22 03:53:30                1.398139e+09
1      2013-11-15 03:45:04                1.396238e+09
2      2013-03-19 23:14:52                1.363735e+09
3      2013-05-21 08:09:28                1.369210e+09
4      2013-01-17 10:14:20                1.358850e+09
5      2013-12-17 03:37:06                1.387424e+09
6      2012-12-16 13:24:32                1.356010e+09
7      2013-07-31 05:34:02                         NaN
8      2013-11-05 04:04:24                         NaN
9      2013-01-16 22:08:03                1.401833e+09
10     2013-12-26 03:55:54                1.388117e+09
11     2014-04-17 23:48:38                         NaN
12     2014-03-30 16:19:38                1.396196e+09
13     2012-10-11 16:14:33                1.350058e+09
14     2013-07-16 21:33:54                         NaN
15     2013-02-11 10:09:50                         NaN
16     2014-04-09 14:39:38                1.397314e+09
17     2013-08-24 00:26:46                         NaN
18     2013-05-24 14:56:36                1.369926e+09
19     2014-03-06 11:46:38                1.401364e+09
20     2013-01-22 12:27:42                1.358858e+09
21     2014-02-10 06:00:46                1.392012e+09
22     2012-08-17 08:30:27                1.345279e+09
23     2013-09-09 22:20:03                1.378765e+09
24     2014-02-25 00:11:13                1.393373e+09
25     2013-07-28 00:53:32                         NaN
26     2014-01-14 17:35:11                1.389807e+09
27     2013-02-11 20:00:25                1.360872e+09
28     2013-09-16 02:08:41                1.379384e+09
29     2013-06-04 00:44:25                1.370307e+09
...                    ...                         ...
11970  2013-05-04 06:54:23                         NaN
11971  2012-09-13 23:23:11                         NaN
11972  2012-10-30 03:09:47                         NaN
11973  2012-12-26 16:42:08                1.356713e+09
11974  2013-03-23 11:10:11                1.400757e+09
11975  2013-12-25 22:01:41                         NaN
11976  2013-09-17 18:58:51                1.379704e+09
11977  2014-04-23 16:28:06                         NaN
11978  2013-01-28 09:26:33                1.359624e+09
11979  2014-02-02 15:23:18                1.397835e+09
11980  2013-03-05 01:53:48                1.364868e+09
11981  2013-12-06 14:39:15                1.386341e+09
11982  2013-07-30 00:23:36                1.375144e+09
11983  2014-02-11 21:26:11                1.392154e+09
11984  2013-07-08 17:23:26                         NaN
11985  2012-06-24 01:02:14                1.341105e+09
11986  2013-03-15 03:21:01                1.363318e+09
11987  2014-03-15 11:04:47                1.401621e+09
11988  2013-09-02 11:24:33                1.378553e+09
11989  2013-07-05 21:00:48                1.373144e+09
11990  2014-04-20 14:22:45                1.401460e+09
11991  2014-04-09 19:39:56                1.397245e+09
11992  2013-03-28 23:24:21                         NaN
11993  2012-06-05 04:46:16                         NaN
11994  2013-10-21 13:33:17                1.382449e+09
11995  2013-09-06 06:14:15                1.378448e+09
11996  2013-01-10 18:28:37                1.358275e+09
11997  2014-04-27 12:45:16                1.398603e+09
11998  2012-05-31 11:55:59                1.338638e+09
11999  2014-01-26 08:57:12                1.390727e+09

[12000 rows x 2 columns]

In [12]:
#convert 'creation_time' and 'last_session_creation_time' to datetime
import datetime
# set creation_time
df_users['creation_time'] = pd.to_datetime(df_users['creation_time'])
#last_session_creation_time is a unix time stamp, so use map to convert to datetime
df_users['last_session_creation_time'] = pd.to_datetime(df_users['last_session_creation_time'],unit='s')

In [13]:
df_users[['creation_time','last_session_creation_time']]

creation_time last_session_creation_time
0     2014-04-22 03:53:30        2014-04-22 03:53:30
1     2013-11-15 03:45:04        2014-03-31 03:45:04
2     2013-03-19 23:14:52        2013-03-19 23:14:52
3     2013-05-21 08:09:28        2013-05-22 08:09:28
4     2013-01-17 10:14:20        2013-01-22 10:14:20
5     2013-12-17 03:37:06        2013-12-19 03:37:06
6     2012-12-16 13:24:32        2012-12-20 13:24:32
7     2013-07-31 05:34:02                        NaT
8     2013-11-05 04:04:24                        NaT
9     2013-01-16 22:08:03        2014-06-03 22:08:03
10    2013-12-26 03:55:54        2013-12-27 03:55:54
11    2014-04-17 23:48:38                        NaT
12    2014-03-30 16:19:38        2014-03-30 16:19:38
13    2012-10-11 16:14:33        2012-10-12 16:14:33
14    2013-07-16 21:33:54                        NaT
15    2013-02-11 10:09:50                        NaT
16    2014-04-09 14:39:38        2014-04-12 14:39:38
17    2013-08-24 00:26:46                        NaT
18    2013-05-24 14:56:36        2013-05-30 14:56:36
19    2014-03-06 11:46:38        2014-05-29 11:46:38
20    2013-01-22 12:27:42        2013-01-22 12:27:42
21    2014-02-10 06:00:46        2014-02-10 06:00:46
22    2012-08-17 08:30:27        2012-08-18 08:30:27
23    2013-09-09 22:20:03        2013-09-09 22:20:03
24    2014-02-25 00:11:13        2014-02-26 00:11:13
25    2013-07-28 00:53:32                        NaT
26    2014-01-14 17:35:11        2014-01-15 17:35:11
27    2013-02-11 20:00:25        2013-02-14 20:00:25
28    2013-09-16 02:08:41        2013-09-17 02:08:41
29    2013-06-04 00:44:25        2013-06-04 00:44:25
...                   ...                        ...
11970 2013-05-04 06:54:23                        NaT
11971 2012-09-13 23:23:11                        NaT
11972 2012-10-30 03:09:47                        NaT
11973 2012-12-26 16:42:08        2012-12-28 16:42:08
11974 2013-03-23 11:10:11        2014-05-22 11:10:11
11975 2013-12-25 22:01:41                        NaT
11976 2013-09-17 18:58:51        2013-09-20 18:58:51
11977 2014-04-23 16:28:06                        NaT
11978 2013-01-28 09:26:33        2013-01-31 09:26:33
11979 2014-02-02 15:23:18        2014-04-18 15:23:18
11980 2013-03-05 01:53:48        2013-04-02 01:53:48
11981 2013-12-06 14:39:15        2013-12-06 14:39:15
11982 2013-07-30 00:23:36        2013-07-30 00:23:36
11983 2014-02-11 21:26:11        2014-02-11 21:26:11
11984 2013-07-08 17:23:26                        NaT
11985 2012-06-24 01:02:14        2012-07-01 01:02:14
11986 2013-03-15 03:21:01        2013-03-15 03:21:01
11987 2014-03-15 11:04:47        2014-06-01 11:04:47
11988 2013-09-02 11:24:33        2013-09-07 11:24:33
11989 2013-07-05 21:00:48        2013-07-06 21:00:48
11990 2014-04-20 14:22:45        2014-05-30 14:22:45
11991 2014-04-09 19:39:56        2014-04-11 19:39:56
11992 2013-03-28 23:24:21                        NaT
11993 2012-06-05 04:46:16                        NaT
11994 2013-10-21 13:33:17        2013-10-22 13:33:17
11995 2013-09-06 06:14:15        2013-09-06 06:14:15
11996 2013-01-10 18:28:37        2013-01-15 18:28:37
11997 2014-04-27 12:45:16        2014-04-27 12:45:16
11998 2012-05-31 11:55:59        2012-06-02 11:55:59
11999 2014-01-26 08:57:12        2014-01-26 08:57:12

[12000 rows x 2 columns]

In [14]:
#creating new feature, usage_length, which indicates how long a user has been active
df_users['usage_length'] = (df_users['last_session_creation_time'] - df_users['creation_time']).map(lambda x: x.total_seconds())

In [15]:
#creat dummies for 'creation_source' 

In [16]:
creation_source_dummies=pd.get_dummies(df_users['creation_source'])

In [17]:
df_new = pd.concat([df_users,creation_source_dummies], axis=1)

In [18]:
df_new.columns

Index(['object_id', 'creation_time', 'name', 'email', 'creation_source',
       'last_session_creation_time', 'opted_in_to_mailing_list',
       'enabled_for_marketing_drip', 'org_id', 'invited_by_user_id', 'adopted',
       'usage_length', 'GUEST_INVITE', 'ORG_INVITE', 'PERSONAL_PROJECTS',
       'SIGNUP', 'SIGNUP_GOOGLE_AUTH'],
      dtype='object')

In [19]:
df_new.loc[df_new['invited_by_user_id'].isnull(),'invited_by_user_id'] = 0

In [20]:
df_new.loc[df_new['invited_by_user_id']!=0,'invited_by_user_id'] = 1

In [21]:
b = df_new.dropna()

In [22]:
b.dtypes

object_id                              int64
creation_time                 datetime64[ns]
name                                  object
email                                 object
creation_source                       object
last_session_creation_time    datetime64[ns]
opted_in_to_mailing_list               int64
enabled_for_marketing_drip             int64
org_id                                 int64
invited_by_user_id                   float64
adopted                                int64
usage_length                         float64
GUEST_INVITE                           uint8
ORG_INVITE                             uint8
PERSONAL_PROJECTS                      uint8
SIGNUP                                 uint8
SIGNUP_GOOGLE_AUTH                     uint8
dtype: object

In [23]:
c=b.drop(['creation_time','name', 'email','last_session_creation_time', 'creation_source'], axis=1)

In [24]:
d = c.set_index('object_id')

In [25]:
d

opted_in_to_mailing_list  enabled_for_marketing_drip  org_id  \
object_id                                                                 
1                                 1                           0      11   
2                                 0                           0       1   
3                                 0                           0      94   
4                                 0                           0       1   
5                                 0                           0     193   
6                                 0                           0     197   
7                                 0                           1      37   
10                                1                           1     318   
11                                0                           0      69   
13                                0                           0     254   
14                                0                           0       0   
17                                1                           0     175   
19                                1                           0       0   
20                                0                           0      58   
21                                0                           0      54   
22                                0                           0       7   
23                                1                           0       6   
24                                1                           0     123   
25                                1                           0      81   
27                                0                           0     134   
28                                0                           0       6   
29                                0                           0      92   
30                                0                           0     251   
31                                0                           0     283   
33                                0                           0     401   
36                                1                           0     109   
37                                0                           0     276   
41                                0                           0      64   
42                                1                           0     235   
43                                0                           0      63   
...                             ...                         ...     ...   
11961                             0                           0       2   
11962                             1                           1      21   
11963                             1                           0      27   
11964                             0                           0       0   
11965                             0                           0      65   
11967                             0                           0      15   
11968                             1                           1     273   
11969                             1                           1      52   
11974                             0                           0     167   
11975                             1                           0      31   
11977                             0                           0     144   
11979                             0                           0       2   
11980                             0                           0     406   
11981                             0                           0     110   
11982                             1                           1      57   
11983                             0                           0     234   
11984                             0                           0     170   
11986                             0                           0     111   
11987                             0                           0       1   
11988                             0                           0     114   
11989                             1 

In [26]:
y=d.pop('adopted')

In [27]:
X=d

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)

In [29]:
# KNeighborsClassifier

param_grid = {'n_neighbors': np.arange(1,50), 'p':[2, 3]}

knn = KNeighborsClassifier()
knn_cv = GridSearchCV(knn, param_grid, cv=5)

knn_cv.fit(X_train, y_train)

# Predict the labels of the test data: y_pred
y_pred = knn_cv.predict(X_test)

# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1407   27]
 [  45  286]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.98      1434
          1       0.91      0.86      0.89       331

avg / total       0.96      0.96      0.96      1765



In [30]:
# DecisionTreeClassifier

param_grid = {'max_depth':[3,5,8,15,25,30,None],
              'max_features': ['auto', 'sqrt', 'log2', None],
              'min_samples_leaf': [1,2,5,10],
              'min_samples_split': [2,5,10,15,100],
              'criterion': ['gini', 'entropy']}

tree = DecisionTreeClassifier()
tree_cv = GridSearchCV(tree, param_grid, cv=5)

tree_cv.fit(X_train, y_train)
# Predict the labels of the test data: y_pred
y_pred = tree_cv.predict(X_test)

# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[1398   36]
 [  42  289]]
             precision    recall  f1-score   support

          0       0.97      0.97      0.97      1434
          1       0.89      0.87      0.88       331

avg / total       0.96      0.96      0.96      1765



In [31]:
print(tree_cv.best_params_)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 10, 'min_samples_split': 2}


In [32]:
tree_clf=DecisionTreeClassifier(criterion='entropy', max_depth= 5, max_features = None, min_samples_leaf=10, min_samples_split= 2)
tree_clf.fit(X_train, y_train)
fi = pd.DataFrame(list(zip(X.columns, tree_clf.feature_importances_)), columns = ['feature', 'importance'])

In [33]:
fi.sort_values('importance',ascending=False)

feature  importance
4                usage_length    0.987779
2                      org_id    0.009469
9          SIGNUP_GOOGLE_AUTH    0.000832
3          invited_by_user_id    0.000781
7           PERSONAL_PROJECTS    0.000590
0    opted_in_to_mailing_list    0.000550
1  enabled_for_marketing_drip    0.000000
5                GUEST_INVITE    0.000000
6                  ORG_INVITE    0.000000
8                      SIGNUP    0.000000

In [34]:
# RandomForestClassifier

param_grid = {"max_depth": [5,8,15,25,30,None], 
              "min_samples_leaf": [1,2,5,10],
              "min_samples_split": [2,5,10,15,100],
              'max_features': ['auto', 'sqrt', 'log2', None],
              "n_estimators": [10,20,100],
              'criterion': ['gini', 'entropy']}
rfc = RandomForestClassifier()
rfc_cv = GridSearchCV(rfc, param_grid, cv=5)

# Fit the classifier to the training data
rfc_cv.fit(X_train, y_train)
# Predict the labels of the test data: y_pred
y_pred = rfc_cv.predict(X_test)

# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1404   30]
 [  44  287]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.97      1434
          1       0.91      0.87      0.89       331

avg / total       0.96      0.96      0.96      1765



In [35]:
# LogisticRegression

param_grid = {'C': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100,1000],
              'penalty': ['l1', 'l2']}

# Create the classifier: logreg
logreg = LogisticRegression()

logreg_cv = GridSearchCV(logreg, param_grid, cv=5)

# Fit the classifier to the training data
logreg_cv.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg_cv.predict(X_test)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
#print(logreg_cv.feature_importances_)

[[1410   24]
 [  44  287]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.98      1434
          1       0.92      0.87      0.89       331

avg / total       0.96      0.96      0.96      1765



As we can see all the models above perform about the same good. The most important feature is 'usage_lenght'. Based on this, I would recommend encourage existing users to log in and use their accounts.
The next important feature is how user signed up. Google Authentication, guest inviation and personal projects have the highest user adoption rate. Encouraging users to use Google Authentication, invite others, and offer people to work on their personal projects might be effective for future user adoption.